-- apply changes
create table t_user (
  id                            bigint generated by default as identity not null,
  timezone                      varchar(255),
  constraint pk_t_user primary key (id)
);

