name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: "Build JAR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

  create-nightly-release:
    name: "Create Nightly Release"
    runs-on: ubuntu-latest
    steps:
      - name: Rename output file
        run: find build/libs -maxdepth 1 -name "*all*" | xargs -I '{}' mv {} build/libs/monty.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          title: "Monty Nightly Release `${{ github.sha }}`"
          prerelease: true
          files: |
            build/libs/monty.jar

  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Rename output file
        run: find build/libs -maxdepth 1 -name "*all*" | xargs -I '{}' mv {} build/libs/monty.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: false
          files: |
            build/libs/monty.jar