name: "Pre-release (Nightly)"

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - '([0-9]){4}\.([0-9]){2}\.([0-9]){2}'

jobs:
  pre_release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Rename output file
        run: find build/libs -maxdepth 1 -name "*all*" | xargs -I '{}' mv {} build/libs/monty.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Monty Nightly Release"
          files: |
            build/libs/monty.jar