name: Pre-release (Nightly)

on:
  push:
    tags-ignore:
      - "*"

jobs:
  prerelease:
    - name: Checkout project sources
      uses: actions/checkout@v2

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Rename output file
      if: state == "release"
      run: mv "build/libs/monty-*-all.jar" "build/libs/monty.jar"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Monty Nightly Release"
          files:
            - build/libs/monty.jar