name: Tagged Release

on:
  push:
    tags:
      - '([0-9]){4}\.([0-9]){2}\.([0-9]){2}' # matches [year].[month].[day]


jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Rename output file
        if: state == "release"
        run: mv "build/libs/monty-*-all.jar" "build/libs/monty.jar"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            build/libs/monty.jar